
export enum ETaskTypeAction {
  TASK_LIST = 'TASK_LIST',
  TASK_EDIT_LIST = 'TASK_EDIT_LIST',
  TASK_BILLABLE = 'TASK_BILLABLE',
  TASK_BILLABLE_ALL = 'TASK_BILLABLE_ALL',
  TASK_RESET_LIST = 'TASK_RESET_LIST',
  TASK_MOVE_FROM_CAN_BILLABLE_TO_CANNOT_BILLABLE_LIST = 'TASK_CAN_BILLABLE',
  TASK_MOVE_FROM_CANNOT_BILLABLE_TO_CAN_BILLABLE_LIST = 'TASK_CANNOT_BILLABLE',
  LOADING = 'IS_LOADING',
  ERROR = 'ERROR'
}
