
export enum EMemberTypeAction {
  MEMBER_LIST = 'MEMBER_LIST',
  MEMBER_SELECTED = 'MEMBER_SELECTED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  UPDATE_SELECTED_MEMBER_LIST = 'MEMBER_UPDATE_SELECTED_LIST',
  EDIT_SELECTED_MEMBER = 'EDIT_SELECTED_MEMBER',
  MEMBER_UPDATE_TYPE = 'MEMBER_UPDATE_TYPE',
  ALL_BRANCH_FILTER = 'ALL_BRANCH_FILTER',
  LOADING = 'IS_LOADING',
  ERROR = 'ERROR'
}
