
export enum EProjectTypeAction {
  PROJECTS_LIST = 'PROJECTS_LIST',
  PROJECTS_QUANTI = 'PROJECTS_QUANTI',
  PROJECT_EDIT_INFO = 'PROJECT_EDIT_INFO',
  PROJECTS_VIEW_TEAM = 'PROJECTS_VIEW_TEAM',
  PROJECTS_VIEW_TASK = 'PROJECTS_VIEW_TASK',
  SET_PROJECT_ID = 'SET_PROJECT_ID',
  LOADING = 'IS_LOADING',
  CREATE_EDIT_LOADING = 'CREATE_EDIT_LOADING',
  REFRESH = 'REFRESH',
  ERROR = 'ERROR'
}
