//  general
export enum EGeneralTypeAction {
  PROJECT_CUSTOMER = 'PROJECT_CUSTOMER',
  PROJECT_NAME = 'PROJECT_NAME',
  PROJECT_CODE = 'PROJECT_CODE',
  TIME_START = 'TIME_START',
  TIME_END = 'TIME_END',
  NOTE = 'NOTE',
  ALL_USER = 'ALL_USER',
  PROJECT_TYPE = 'PROJECT_TYPE',
  UPDATE_GENERAL_FORM_INFO = 'UPDATE_GENERAL_FORM_INFO',
}
